activation: ReLU
batch_size: 32
drop_last_loader: false
dropout_prob_theta: 0.0
early_stop_patience_steps: -1
futr_exog_list: null
h: 336
hist_exog_list: null
input_size: 672
interpolation_mode: linear
learning_rate: 0.001
loss: !!python/object:neuralforecast.losses.pytorch.MQLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - - - quantiles
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDwAAADEwNTU1MzEyNzM3NzQwOHECWAMAAABjcHVxA0sFTnRxBFEugAJdcQBYDwAAADEw
              NTU1MzEyNzM3NzQwOHEBYS4FAAAAAAAAAAAAAD/NzMw8Urj+PtejAD+amXk/
          - 0
          - !!python/tuple
            - 5
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  is_distribution_output: false
  output_names:
  - -median
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADkAAAA1AAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U7
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 28
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADAAAAAuAAAANQAAAA==
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U7
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 28
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADAAAAAuAAAANQAAAA==
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADkAAAA1AAAA
  outputsize_multiplier: 5
  training: true
max_epochs: 50
max_steps: 1000
mlp_units:
- &id001
  - 512
  - 512
- *id001
- *id001
n_blocks:
- 1
- 1
- 1
n_freq_downsample:
- 4
- 2
- 1
n_pool_kernel_size:
- 2
- 2
- 1
num_lr_decays: 3
num_workers_loader: 0
pooling_mode: MaxPool1d
random_seed: 1
scaler_type: identity
stack_types:
- identity
- identity
- identity
stat_exog_list: null
step_size: 1
val_check_steps: 100
valid_batch_size: null
valid_loss: null
windows_batch_size: 1024
